// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212193619_AdcPacientesVinculados")]
    partial class AdcPacientesVinculados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel.Paciente", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoPaciente")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PsicologoResponsavelId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QtdAcessos")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("Paciente");

                    b.HasData(
                        new
                        {
                            UsuarioId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            ContatoEmergencia = "14999009858",
                            HistoricoPaciente = "historico paciente",
                            PsicologoResponsavelId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            QtdAcessos = 0
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel.RegistroSessao", b =>
                {
                    b.Property<int>("RegistroSessaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistroSessaoId"));

                    b.Property<DateTime>("DataHoraSessao")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("DuracaoSessao")
                        .HasColumnType("time(6)");

                    b.Property<string>("PacienteId")
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoSessao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RegistroSessaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroSessao");

                    b.HasData(
                        new
                        {
                            RegistroSessaoId = -1,
                            DataHoraSessao = new DateTime(2026, 4, 1, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            DuracaoSessao = new TimeSpan(50),
                            PacienteId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            ResumoSessao = "Resumo Sessao 1"
                        },
                        new
                        {
                            RegistroSessaoId = -2,
                            DataHoraSessao = new DateTime(2026, 5, 1, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            DuracaoSessao = new TimeSpan(50),
                            PacienteId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            ResumoSessao = "Resumo Sessao 2"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel.Psicologo", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AbordagensTerapeuticas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CondicoesTerapeuticas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ModalidadeDeAtendimento")
                        .HasColumnType("int");

                    b.Property<string>("TiposPacientes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Psicologo");

                    b.HasData(
                        new
                        {
                            UsuarioId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            AbordagensTerapeuticas = "1,2",
                            CRP = "12345",
                            CondicoesTerapeuticas = "2,1",
                            Descricao = "Psicóloga dedicada a ajudar pacientes a superar desafios emocionais e alcançar bem-estar mental.",
                            ModalidadeDeAtendimento = 1,
                            TiposPacientes = "3,2"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.RPD.EmocaoRegistro", b =>
                {
                    b.Property<int>("EmocaoRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmocaoRegistroId"));

                    b.Property<int>("Emocao")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeFinal")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeInicial")
                        .HasColumnType("int");

                    b.Property<int>("RegistroPensamentoId")
                        .HasColumnType("int");

                    b.HasKey("EmocaoRegistroId");

                    b.HasIndex("RegistroPensamentoId");

                    b.ToTable("EmocaoRegistro");
                });

            modelBuilder.Entity("Connectamente.API.Models.RPD.RegistroPensamento", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<string>("CaminhoArquivoRegistro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RegistroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5458aee0-71ca-4f08-88e8-0f03d18d6960",
                            DataNascimento = new DateOnly(2002, 4, 1),
                            Email = "anajuliamattos02@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/psicologo.png",
                            LockoutEnabled = true,
                            Nome = "Ana Julia",
                            NormalizedEmail = "ANAJULIAMATTOS02@GMAIL.COM",
                            NormalizedUserName = "ANAJULIAMATTOS02@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumber = "14920044824",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15cfe30f-1dac-404e-85e6-02159dbed489",
                            Sobrenome = " Reis de Mattos",
                            TipoPerfil = 2,
                            TwoFactorEnabled = false,
                            UserName = "anajuliamattos02@gmail.com"
                        },
                        new
                        {
                            Id = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7cb3541f-0085-4145-b6d7-3e9ae3a300a5",
                            DataNascimento = new DateOnly(2001, 12, 19),
                            Email = "tainaravitsantos28@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/paciente.png",
                            LockoutEnabled = true,
                            Nome = "Tainara Vitoria",
                            NormalizedEmail = "TAINARAVITSANTOS28@GMAIL.COM",
                            NormalizedUserName = "TAINARAVITSANTOS28@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumber = "14988060308",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b0faad3-6502-4325-94ee-33aab11905d7",
                            Sobrenome = " dos Santos",
                            TipoPerfil = 1,
                            TwoFactorEnabled = false,
                            UserName = "tainaravitsantos28@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Psicologo",
                            NormalizedName = "PSICOLOGO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Paciente",
                            NormalizedName = "PACIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel.Paciente", b =>
                {
                    b.HasOne("Connectamente.API.Models.PsicologoModel.Psicologo", "PsicologoResponsavel")
                        .WithMany("PacientesVinculados")
                        .HasForeignKey("PsicologoResponsavelId");

                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsicologoResponsavel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacienteModel.RegistroSessao", b =>
                {
                    b.HasOne("Connectamente.API.Models.PacienteModel.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel.Psicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.RPD.EmocaoRegistro", b =>
                {
                    b.HasOne("Connectamente.API.Models.RPD.RegistroPensamento", "RegistroPensamento")
                        .WithMany()
                        .HasForeignKey("RegistroPensamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.RPD.RegistroPensamento", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Connectamente.API.Models.PsicologoModel.Psicologo", b =>
                {
                    b.Navigation("PacientesVinculados");
                });
#pragma warning restore 612, 618
        }
    }
}
