// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107154744_AdicionandoNovasTabelasPsicologo")]
    partial class AdicionandoNovasTabelasPsicologo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.AbordagemTerapeutica", b =>
                {
                    b.Property<int>("IdAbordagemTerapeutica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAbordagemTerapeutica"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdAbordagemTerapeutica");

                    b.ToTable("AbordagemTerapeutica");

                    b.HasData(
                        new
                        {
                            IdAbordagemTerapeutica = 1,
                            Descricao = "Abordagem prática e focada em objetivos, que identifica e modifica padrões de pensamentos (cognições) e comportamentos negativos, sendo eficaz para ansiedade, depressão e TOC, com o terapeuta tendo um papel mais ativo.",
                            Nome = "Terapia Cognitivo-Comportamental"
                        },
                        new
                        {
                            IdAbordagemTerapeutica = 2,
                            Descricao = "Baseada em Carl Rogers e Abraham Maslow, acredita na capacidade inata do indivíduo para o crescimento, focando na autoaceitação e realização do potencial humano, com o terapeuta oferecendo empatia e consideração positiva incondicional.",
                            Nome = "Humanista/Centrada na Pessoa"
                        },
                        new
                        {
                            IdAbordagemTerapeutica = 3,
                            Descricao = "A psicoterapia fenomenológico-existencial é uma abordagem que combina a filosofia da fenomenologia e do existencialismo para compreender a experiência humana. ",
                            Nome = "Psicoterapia Fenomenológico-Existencial"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.CondicaoTerapeutica", b =>
                {
                    b.Property<int>("IdCondicaoTerapeutica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCondicaoTerapeutica"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCondicaoTerapeutica");

                    b.ToTable("CondicaoTerapeutica");

                    b.HasData(
                        new
                        {
                            IdCondicaoTerapeutica = 1,
                            Descricao = "Atendimento psicológico com foco nas vivências e desafios específicos da comunidade LGBTQIAPN+. O objetivo é oferecer um acolhimento livre de preconceitos, auxiliando em questões de aceitação, identidade de gênero, orientação sexual, além de fortalecer a autoestima e o enfrentamento de violências sociais.",
                            Nome = "LGBTQIAPN+"
                        },
                        new
                        {
                            IdCondicaoTerapeutica = 2,
                            Descricao = "O luto é um processo natural diante de uma perda significativa, mas que pode ser extremamente doloroso e paralisante. A terapia oferece um espaço seguro para vivenciar as etapas do pesar, ajudando o paciente a ressignificar a perda e a encontrar formas de seguir em frente com a memória do que se foi.",
                            Nome = "Luto"
                        },
                        new
                        {
                            IdCondicaoTerapeutica = 3,
                            Descricao = "A depressão vai além da tristeza profunda; é um transtorno que afeta o humor, a energia e o interesse pela vida. O acompanhamento terapêutico busca identificar as causas desses sentimentos, oferecer suporte emocional e desenvolver estratégias para recuperar a qualidade de vida e o bem-estar mental.",
                            Nome = "Depressão"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.Property<int>("IdEmocaoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmocaoRegistro"));

                    b.Property<int>("Emocao")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeFinal")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeInicial")
                        .HasColumnType("int");

                    b.Property<int>("RegistroPensamentoId")
                        .HasColumnType("int");

                    b.HasKey("IdEmocaoRegistro");

                    b.HasIndex("RegistroPensamentoId");

                    b.ToTable("EmocaoRegistro");
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ModalidadeDeAtendimento")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Psicologo");

                    b.HasData(
                        new
                        {
                            UsuarioId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            CRP = "12345",
                            Descricao = "Psicóloga dedicada a ajudar pacientes a superar desafios emocionais e alcançar bem-estar mental.",
                            ModalidadeDeAtendimento = 1
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<string>("CaminhoArquivoRegistro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.TipoPaciente", b =>
                {
                    b.Property<int>("IdTipoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoPaciente"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdTipoPaciente");

                    b.ToTable("TipoPaciente");

                    b.HasData(
                        new
                        {
                            IdTipoPaciente = 1,
                            Descricao = "O atendimento infantil utiliza o brincar como a principal ferramenta de comunicação. Através da ludoterapia, o psicólogo auxilia a criança a expressar suas emoções, medos e conflitos, trabalhando questões comportamentais, dificuldades de aprendizagem e socialização em conjunto com a orientação aos pais ou responsáveis.",
                            Nome = "Infantil+"
                        },
                        new
                        {
                            IdTipoPaciente = 2,
                            Descricao = "Focada na dinâmica do relacionamento, a terapia de casal busca mediar conflitos e melhorar a comunicação entre os parceiros. O objetivo é compreender os padrões de interação, fortalecer o vínculo afetivo ou auxiliar em processos de separação de forma saudável, proporcionando um espaço neutro de escuta e acolhimento para ambos.",
                            Nome = "Casal"
                        },
                        new
                        {
                            IdTipoPaciente = 3,
                            Descricao = "A psicoterapia para adultos é um processo de autoconhecimento e cuidado com a saúde mental. Foca no enfrentamento de desafios cotidianos, como estresse, ansiedade, questões de carreira e relacionamentos, auxiliando o paciente a desenvolver recursos internos para lidar com suas emoções e tomar decisões mais conscientes e alinhadas aos seus valores.",
                            Nome = "Adultos"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PsicologoResponsavelId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QtdAcessos")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68fb7d10-901a-4105-9534-38438cef41ef",
                            DataNascimento = new DateOnly(2002, 4, 1),
                            Email = "anajuliamattos02@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/psicologo.png",
                            LockoutEnabled = true,
                            Nome = "Ana Julia",
                            NormalizedEmail = "ANAJULIAMATTOS02@GMAIL.COM",
                            NormalizedUserName = "anajuliamattos02@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9M2YkpzA924MCFe1W5quROpOs9bE264K3UhvTAEmDpvm70TSJ0c+35JzXVmQha6w==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "1ddfa952-0e5c-4124-9476-928b5be87413",
                            Sobrenome = " Reis de Mattos",
                            TipoPerfil = 2,
                            TwoFactorEnabled = false,
                            UserName = "anajuliamattos02@gmail.com"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17c5b11a-f065-436c-b4fd-da367614f4f0",
                            DataNascimento = new DateOnly(2001, 12, 19),
                            Email = "tainaravitsantos28@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/paciente.png",
                            LockoutEnabled = true,
                            Nome = "Tainara Vitoria",
                            NormalizedEmail = "TAINARAVITSANTOS28@GMAIL.COM",
                            NormalizedUserName = "tainaravitsantos28@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDf1Z7YAFUr30edMYPDBUxY6Bwy6xjD6Vt2uRnDyou/bjwPTnUmHfjPu15yUfnWkbw==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "2faf6c2d-71b6-4c2a-a233-70fe352e0fe5",
                            Sobrenome = " dos Santos",
                            TipoPerfil = 1,
                            TwoFactorEnabled = false,
                            UserName = "tainaravitsantos28@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Psicologo",
                            NormalizedName = "PSICOLOGO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Paciente",
                            NormalizedName = "PACIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PsicologoAbordagem", b =>
                {
                    b.Property<int>("AbordagemTerapeuticaId")
                        .HasColumnType("int");

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AbordagemTerapeuticaId", "PsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("PsicologoAbordagem");

                    b.HasData(
                        new
                        {
                            AbordagemTerapeuticaId = 1,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            AbordagemTerapeuticaId = 2,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        });
                });

            modelBuilder.Entity("PsicologoCondicaoTratada", b =>
                {
                    b.Property<int>("CondicaoTerapeuticaId")
                        .HasColumnType("int");

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CondicaoTerapeuticaId", "PsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("PsicologoCondicaoTratada");

                    b.HasData(
                        new
                        {
                            CondicaoTerapeuticaId = 1,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            CondicaoTerapeuticaId = 2,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        });
                });

            modelBuilder.Entity("PsicologoTipoPaciente", b =>
                {
                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoPacienteId")
                        .HasColumnType("int");

                    b.HasKey("PsicologoId", "TipoPacienteId");

                    b.HasIndex("TipoPacienteId");

                    b.ToTable("PsicologoTipoPaciente");

                    b.HasData(
                        new
                        {
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            TipoPacienteId = 1
                        },
                        new
                        {
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            TipoPacienteId = 2
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.HasOne("Connectamente.API.Models.RegistroPensamento", "RegistroPensamento")
                        .WithMany()
                        .HasForeignKey("RegistroPensamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "PsicologoResponsavel")
                        .WithMany()
                        .HasForeignKey("PsicologoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PsicologoAbordagem", b =>
                {
                    b.HasOne("Connectamente.API.Models.AbordagemTerapeutica", null)
                        .WithMany()
                        .HasForeignKey("AbordagemTerapeuticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoAbordagem_AbordagemTerapeutica");

                    b.HasOne("Connectamente.API.Models.Psicologo", null)
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoAbordagem_Psicologo");
                });

            modelBuilder.Entity("PsicologoCondicaoTratada", b =>
                {
                    b.HasOne("Connectamente.API.Models.CondicaoTerapeutica", null)
                        .WithMany()
                        .HasForeignKey("CondicaoTerapeuticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoCondicao_CondicaoTerapeutica");

                    b.HasOne("Connectamente.API.Models.Psicologo", null)
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoCondicao_Psicologo");
                });

            modelBuilder.Entity("PsicologoTipoPaciente", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", null)
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoPaciente_Psicologo");

                    b.HasOne("Connectamente.API.Models.TipoPaciente", null)
                        .WithMany()
                        .HasForeignKey("TipoPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoPaciente_TipoPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
