// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.AbordagemTerapeutica", b =>
                {
                    b.Property<uint>("IdAbordagemTerapeutica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdAbordagemTerapeutica"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdAbordagemTerapeutica");

                    b.ToTable("AbordagemTerapeutica");

                    b.HasData(
                        new
                        {
                            IdAbordagemTerapeutica = 1u,
                            Descricao = "Abordagem prática e focada em objetivos, que identifica e modifica padrões de pensamentos (cognições) e comportamentos negativos, sendo eficaz para ansiedade, depressão e TOC, com o terapeuta tendo um papel mais ativo.",
                            Nome = "Terapia Cognitivo-Comportamental"
                        },
                        new
                        {
                            IdAbordagemTerapeutica = 2u,
                            Descricao = "Baseada em Carl Rogers e Abraham Maslow, acredita na capacidade inata do indivíduo para o crescimento, focando na autoaceitação e realização do potencial humano, com o terapeuta oferecendo empatia e consideração positiva incondicional.",
                            Nome = "Humanista/Centrada na Pessoa"
                        },
                        new
                        {
                            IdAbordagemTerapeutica = 3u,
                            Descricao = "A psicoterapia fenomenológico-existencial é uma abordagem que combina a filosofia da fenomenologia e do existencialismo para compreender a experiência humana. ",
                            Nome = "Psicoterapia Fenomenológico-Existencial"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.Property<uint>("IdEmocaoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdEmocaoRegistro"));

                    b.Property<int>("Emocao")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeFinal")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeInicial")
                        .HasColumnType("int");

                    b.Property<uint>("RegistroPensamentoId")
                        .HasColumnType("int unsigned");

                    b.HasKey("IdEmocaoRegistro");

                    b.HasIndex("RegistroPensamentoId");

                    b.ToTable("EmocaoRegistro");
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ModalidadeDeAtendimento")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Psicologo");

                    b.HasData(
                        new
                        {
                            UsuarioId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            CRP = "12345",
                            Descricao = "Psicóloga dedicada a ajudar pacientes a superar desafios emocionais e alcançar bem-estar mental.",
                            ModalidadeDeAtendimento = 1
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.Property<uint>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdRegistro"));

                    b.Property<string>("CaminhoArquivoRegistro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PsicologoResponsavelId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QtdAcessos")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2abb668e-e295-4de2-8d3d-cca9d5e06e9d",
                            DataNascimento = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anajuliamattos02@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/psicologo.png",
                            LockoutEnabled = true,
                            Nome = "Ana Julia",
                            NormalizedEmail = "ANAJULIAMATTOS02@GMAIL.COM",
                            NormalizedUserName = "anajuliamattos02@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMlotJhf7tuYj550eWA3j2fFhNJYo8M9I7hkFeidy1J0W0Obkw+EWl1FYn50m+buEg==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "54c54f79-5fc8-4a6a-912d-0d3b729bd791",
                            Sobrenome = " Reis de Mattos",
                            TipoPerfil = 2,
                            TwoFactorEnabled = false,
                            UserName = "anajuliamattos02@gmail.com"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "155f7a84-4f85-4f31-b905-974af2376791",
                            DataNascimento = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tainaravitsantos28@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/paciente.png",
                            LockoutEnabled = true,
                            Nome = "Tainara Vitoria",
                            NormalizedEmail = "TAINARAVITSANTOS28@GMAIL.COM",
                            NormalizedUserName = "tainaravitsantos28@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKigodQB15y6Q0IZlTvFmQzyUfm8thlS49uq6aaaihOmJw0jnBLefVRMQmvCJw1Z3g==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "c9dfd88f-9bb9-419f-a568-8b3a91e578b2",
                            Sobrenome = " dos Santos",
                            TipoPerfil = 1,
                            TwoFactorEnabled = false,
                            UserName = "tainaravitsantos28@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Psicologo",
                            NormalizedName = "PSICOLOGO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Paciente",
                            NormalizedName = "PACIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PsicologoAbordagem", b =>
                {
                    b.Property<uint>("AbordagemTerapeuticaId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AbordagemTerapeuticaId", "PsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("PsicologoAbordagem");

                    b.HasData(
                        new
                        {
                            AbordagemTerapeuticaId = 1u,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            AbordagemTerapeuticaId = 2u,
                            PsicologoId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.HasOne("Connectamente.API.Models.RegistroPensamento", "RegistroPensamento")
                        .WithMany()
                        .HasForeignKey("RegistroPensamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "PsicologoResponsavel")
                        .WithMany()
                        .HasForeignKey("PsicologoResponsavelId");

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PsicologoAbordagem", b =>
                {
                    b.HasOne("Connectamente.API.Models.AbordagemTerapeutica", null)
                        .WithMany()
                        .HasForeignKey("AbordagemTerapeuticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoAbordagem_AbordagemTerapeutica");

                    b.HasOne("Connectamente.API.Models.Psicologo", null)
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_PsicologoAbordagem_Psicologo");
                });
#pragma warning restore 612, 618
        }
    }
}
