// <auto-generated />
using System;
using Connectamente.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connectamente.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Connectamente.API.Models.AbordagemPsicologo", b =>
                {
                    b.Property<int>("AbordagemPsicologoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AbordagemPsicologoId"));

                    b.Property<int>("AbordagemTerapeutica")
                        .HasColumnType("int");

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AbordagemPsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("AbordagemPsicologo");

                    b.HasData(
                        new
                        {
                            AbordagemPsicologoId = -1,
                            AbordagemTerapeutica = 0,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        },
                        new
                        {
                            AbordagemPsicologoId = -2,
                            AbordagemTerapeutica = 1,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.CondicaoPsicologo", b =>
                {
                    b.Property<int>("CondicaoPsicologoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CondicaoPsicologoId"));

                    b.Property<int>("CondicaoTerapeutica")
                        .HasColumnType("int");

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CondicaoPsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("CondicaoPsicologo");

                    b.HasData(
                        new
                        {
                            CondicaoPsicologoId = -1,
                            CondicaoTerapeutica = 3,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        },
                        new
                        {
                            CondicaoPsicologoId = -2,
                            CondicaoTerapeutica = 13,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047"
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.Property<int>("EmocaoRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmocaoRegistroId"));

                    b.Property<int>("Emocao")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeFinal")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadeInicial")
                        .HasColumnType("int");

                    b.Property<int>("RegistroPensamentoId")
                        .HasColumnType("int");

                    b.HasKey("EmocaoRegistroId");

                    b.HasIndex("RegistroPensamentoId");

                    b.ToTable("EmocaoRegistro");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacientePsicologo", b =>
                {
                    b.Property<int>("PacientePsicologoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PacientePsicologoId"));

                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoPaciente")
                        .HasColumnType("int");

                    b.HasKey("PacientePsicologoId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("PacientePsicologo");

                    b.HasData(
                        new
                        {
                            PacientePsicologoId = -1,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            TipoPaciente = 6
                        },
                        new
                        {
                            PacientePsicologoId = -2,
                            PsicologoId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            TipoPaciente = 4
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ModalidadeDeAtendimento")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Psicologo");

                    b.HasData(
                        new
                        {
                            UsuarioId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            CRP = "12345",
                            Descricao = "Psicóloga dedicada a ajudar pacientes a superar desafios emocionais e alcançar bem-estar mental.",
                            ModalidadeDeAtendimento = 1
                        });
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<string>("CaminhoArquivoRegistro")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RegistroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PsicologoResponsavelId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QtdAcessos")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5458aee0-71ca-4f08-88e8-0f03d18d6960",
                            DataNascimento = new DateOnly(2002, 4, 1),
                            Email = "anajuliamattos02@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/psicologo.png",
                            LockoutEnabled = true,
                            Nome = "Ana Julia",
                            NormalizedEmail = "ANAJULIAMATTOS02@GMAIL.COM",
                            NormalizedUserName = "ANAJULIAMATTOS02@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "15cfe30f-1dac-404e-85e6-02159dbed489",
                            Sobrenome = " Reis de Mattos",
                            TipoPerfil = 2,
                            TwoFactorEnabled = false,
                            UserName = "anajuliamattos02@gmail.com"
                        },
                        new
                        {
                            Id = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7cb3541f-0085-4145-b6d7-3e9ae3a300a5",
                            DataNascimento = new DateOnly(2001, 12, 19),
                            Email = "tainaravitsantos28@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/paciente.png",
                            LockoutEnabled = true,
                            Nome = "Tainara Vitoria",
                            NormalizedEmail = "TAINARAVITSANTOS28@GMAIL.COM",
                            NormalizedUserName = "TAINARAVITSANTOS28@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9FzXF/zP/9q8m6sF3jKx5T6P6lB6m1z2x3c4v5b6n7m8==",
                            PhoneNumberConfirmed = false,
                            QtdAcessos = 0,
                            SecurityStamp = "5b0faad3-6502-4325-94ee-33aab11905d7",
                            Sobrenome = " dos Santos",
                            TipoPerfil = 1,
                            TwoFactorEnabled = false,
                            UserName = "tainaravitsantos28@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Psicologo",
                            NormalizedName = "PSICOLOGO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Paciente",
                            NormalizedName = "PACIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "70f93f27-32b1-4de5-bee3-b0de2cf80047",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "59de1fac-5ba6-49b0-8849-c97e3c7ba11b",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Connectamente.API.Models.AbordagemPsicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "Psicologo")
                        .WithMany("AbordagensTerapeuticas")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Connectamente.API.Models.CondicaoPsicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "Psicologo")
                        .WithMany("CondicoesTerapeuticas")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Connectamente.API.Models.EmocaoRegistro", b =>
                {
                    b.HasOne("Connectamente.API.Models.RegistroPensamento", "RegistroPensamento")
                        .WithMany()
                        .HasForeignKey("RegistroPensamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPensamento");
                });

            modelBuilder.Entity("Connectamente.API.Models.PacientePsicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "Psicologo")
                        .WithMany("TiposPacientes")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.RegistroPensamento", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Connectamente.API.Models.Usuario", b =>
                {
                    b.HasOne("Connectamente.API.Models.Psicologo", "PsicologoResponsavel")
                        .WithMany()
                        .HasForeignKey("PsicologoResponsavelId");

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Connectamente.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Connectamente.API.Models.Psicologo", b =>
                {
                    b.Navigation("AbordagensTerapeuticas");

                    b.Navigation("CondicoesTerapeuticas");

                    b.Navigation("TiposPacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
