name: .NET CI - Testes Unitários

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET 9 com Cache
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj' 

    - name: Restaurar dependências
      run: dotnet restore Connectamente.API/Connectamente.API.csproj

    - name: Build do projeto
      run: dotnet build Connectamente.API/Connectamente.API.csproj --no-restore --configuration Release

    - name: Rodar Testes Unitários    
      run: dotnet test Connectamente.API/Connectamente.API.csproj --no-build --verbosity normal